---
apiVersion: v1
kind: Service
metadata:
  name: gitdemo-k8s-__CI_ENVIRONMENT_SLUG__
  namespace: gitlab
  labels:
    app: presentation-gitlab-k8s
    ref: __CI_ENVIRONMENT_SLUG__
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8000
      protocol: TCP
  selector:
    app: presentation-gitlab-k8s
    ref: __CI_ENVIRONMENT_SLUG__
